name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gazebo
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          apt-get update \
          && apt-get install -y python3-pip \
          && pip install -U vcstool colcon-common-extensions
      - name: Fetch dependencies
        run: |
          mkdir -p tb4_ws/src
          vcs import tb4_ws/src < dependencies.repos
      - name: Run tests
        run: |
          cd tb4_ws
          colcon test --event-handlers console_direct+
      - name: Gazebo smoke test
        run: |
          set -e
          gzserver --headless-rendering ~/launch/sim.launch.py &
          PID=$!
          sleep 20
          ros2 service call /reset_simulation std_srvs/srv/Empty
          kill $PID
